### ISSUE TITLE
Incompatible with Rails 4.x

### ISSUE THREAD

**Issue by gevans** [jingweno/msgpack_rails#3]
I just updated to the 0.4.0 release of msgpack_rails and it looks like the addition of an ActionController renderer in #1 results in an API compatibility issue in the Rails 4.x series:

```
/opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/msgpack_rails-0.4.0/lib/msgpack_rails.rb:41:in `block in <class:Rails>': undefined method `add_renderer' for ActionController:Module (NoMethodError)
        from /opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/initializable.rb:30:in `instance_exec'
        from /opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/initializable.rb:30:in `run'
        from /opt/boxen/rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/railties-4.1.0/lib/rails/initializable.rb:55:in `block in run_initializers'
        from /opt/boxen/rbenv/versions/2.1.1/lib/ruby/2.1.0/tsort.rb:226:in `block in tsort_each'
        from /opt/boxen/rbenv/versions/2.1.1/lib/ruby/2.1.0/tsort.rb:348:in `block (2 levels) in each_strongly_connected_component'
        from /opt/boxen/rbenv/versions/2.1.1/lib/ruby/2.1.0/tsort.rb:427:in `each_strongly_connected_component_from'
        from /opt/boxen/rbenv/versions/2.1.1/lib/ruby/2.1.0/tsort.rb:347:in `block in each_strongly_connected_component'
```

In Rails 4, `ActionController.add_renderer` was relocated to `ActionController::Renderers.add`. I hacked it a bit by replacing [lines 41-44 of msgpack_rails.rb](https://github.com/jingweno/msgpack_rails/blob/master/lib/msgpack_rails.rb#L41:L44) with:

``` ruby
        renderer = Proc.new do |data, options|
          self.content_type = Mime::MSGPACK
          self.response_body = data.as_msgpack(options)
        end

        if ::Rails::VERSION::MAJOR >= 4 && ::Rails::VERSION::MINOR >= 1
          ::ActionController::Renderers.add(:msgpack, &renderer)
        else
          ::ActionController.add_renderer(:msgpack, &renderer)
        end
```

I would set up [appraisal](https://github.com/thoughtbot/appraisal) and test against Rails 3.2.x, 4.0.x, and 4.1.x but the development dependencies in the gemspec are a bit too restrictive at the moment. So, solutions? Should I open a pull request with support for _only_ Rails 4.1.x or should backwards compatibility be preserved?

Thanks!

**Comment by hiradyazdan** [comment]
@jingweno Does this gem support latest Rails (5, 6) as well?
